def get_openstack_catalog_services() -> list[dict[str, object]]:
    return [
        {
            "id": "ubuntu-vm",
            "provider": "openstack",
            "name": "Ubuntu VM",
            "description": "General purpose Ubuntu virtual machine for application hosting.",
            "recommended_cpu": 2,
            "recommended_ram_gb": 4,
            "recommended_disk_gb": 40,
            "estimated_monthly_cost": 1800,
            "risk_level": "low",
            "packages": [],
            "environment": "dev",
            "app_tag": "ubuntu-vm",
            "public_ip_required": False,
        },
        {
            "id": "python-dev",
            "provider": "openstack",
            "name": "Python Development Environment",
            "description": "Developer VM with Python tooling for backend services and scripts.",
            "recommended_cpu": 4,
            "recommended_ram_gb": 8,
            "recommended_disk_gb": 80,
            "estimated_monthly_cost": 3400,
            "risk_level": "low",
            "packages": ["python", "pip", "venv", "git"],
            "environment": "dev",
            "app_tag": "python-dev",
            "public_ip_required": False,
        },
        {
            "id": "node-dev",
            "provider": "openstack",
            "name": "Node.js Development Environment",
            "description": "Frontend and API development VM with Node.js tooling.",
            "recommended_cpu": 4,
            "recommended_ram_gb": 8,
            "recommended_disk_gb": 80,
            "estimated_monthly_cost": 3400,
            "risk_level": "low",
            "packages": ["nodejs", "npm", "git"],
            "environment": "dev",
            "app_tag": "node-dev",
            "public_ip_required": False,
        },
        {
            "id": "docker-host",
            "provider": "openstack",
            "name": "Docker Host",
            "description": "Container host for running development or staging workloads.",
            "recommended_cpu": 6,
            "recommended_ram_gb": 12,
            "recommended_disk_gb": 120,
            "estimated_monthly_cost": 5100,
            "risk_level": "medium",
            "packages": ["docker", "docker-compose", "git"],
            "environment": "stage",
            "app_tag": "docker-host",
            "public_ip_required": False,
        },
        {
            "id": "postgresql-server",
            "provider": "openstack",
            "name": "PostgreSQL Server",
            "description": "Managed-style PostgreSQL VM for application databases.",
            "recommended_cpu": 4,
            "recommended_ram_gb": 16,
            "recommended_disk_gb": 250,
            "estimated_monthly_cost": 5600,
            "risk_level": "high",
            "packages": ["postgresql"],
            "environment": "stage",
            "app_tag": "postgresql",
            "public_ip_required": False,
        },
        {
            "id": "ai-workstation",
            "provider": "openstack",
            "name": "AI Workstation",
            "description": "High-memory workstation for data science and AI experimentation.",
            "recommended_cpu": 8,
            "recommended_ram_gb": 32,
            "recommended_disk_gb": 300,
            "estimated_monthly_cost": 9200,
            "risk_level": "high",
            "packages": ["python", "jupyter", "pytorch", "cuda-toolkit"],
            "environment": "dev",
            "app_tag": "ai-workstation",
            "public_ip_required": False,
        },
    ]
